### PR TITLE
Changed URI

### PR DESCRIPTION
**Pull request by BramGiesen**
Changed URI to prevent conflict with regular ams-lv2

### CODE REVIEW

**Review by falkTX — CHANGES_REQUESTED** [review]
Please update the ttl files to match

**Comment by falkTX** [comment]
those are all the plugins? just 6?
what happened to the other ones?

we need to ensure those are not published

**Comment by BramGiesen** [comment]
Yes we selected 6 plugins that we thought would be most usable or important to start with. The other ones are still in the regular ams-lv2 package.

**Review by falkTX — APPROVED** [review]
As long as the bundles we are not going to use do not end up being published, it is all good.

**Comment by BramGiesen** [comment]
These changes are no longer required. Instead of changing these URI's, the conflicting plugins will be removed from the other package ams package that contains all ams-lv2 plugins.

**Pull request closed without merging**
